// React/src/App.js
import React, {useState, useCallback} from 'react';
import DataGrid, {Column, Editing, Popup, Form} from 'devextreme-react/data-grid';
import {Item} from 'devextreme-react/form';
import Button from 'devextreme-react/button';
import FileUploader from 'devextreme-react/file-uploader';

import {employees} from './data.js';

const backendURL = "http://localhost:5000/";
let fileUploaderRef = React.createRef();
let imgRef = React.createRef();
let currentCellInfo;

const cellRender = data => {
  return <img src={backendURL + data.value}/>;
}

const onClick = e => {
  // The retry UI/API is not implemented. Use a private API as shown at T611719.
  const fileUploaderInstance = fileUploaderRef.current.instance;
  for (let i = 0; i < fileUploaderInstance._files.length; i++) {
    delete fileUploaderInstance._files[i].uploadStarted;
  }
  fileUploaderInstance._uploadFiles();
};

const onValueChanged = e => {
  const reader = new FileReader();
  reader.onload = function (args) {
    imgRef.current.setAttribute('src', args.target.result);
  }
  reader.readAsDataURL(e.value[0]); // convert to base64 string
};

function App(props) {
  const [retryButtonVisible, setRetryButtonVisible] = useState(false);

  function editCellRender(cellInfo) {
    currentCellInfo = cellInfo;
    return (
      <>
        <img ref={imgRef} className="uploadedImage" src={backendURL + cellInfo.value}/>
        <FileUploader ref={fileUploaderRef} multiple={false} accept="image/*" uploadMode="instantly"
                      uploadUrl={backendURL + "FileUpload/post"} onValueChanged={onValueChanged}
                      onUploaded={onUploaded} onUploadError={onUploadError}/>
        <Button className={"retryButton"} text="Retry" visible={retryButtonVisible} onClick={onClick}/>
      </>
    );
  }

  const onUploaded = useCallback(e => {
    currentCellInfo.setValue("images/employees/" + e.request.responseText);
    setRetryButtonVisible(false);
  }, []);

  const onUploadError = useCallback(e => {
    let xhttp = e.request;
    if (xhttp.status === 400) {
      e.message = e.error.responseText;
    }
    if (xhttp.readyState == 4 && xhttp.status == 0) {
      e.message = "Connection refused";
    }
    setRetryButtonVisible(true);
  }, []);

  const onEditCanceled = useCallback(e => {
    if (retryButtonVisible)
      setRetryButtonVisible(false);
  }, [])

  const onSaved = useCallback(e => {
    if (retryButtonVisible)
      setRetryButtonVisible(false);
  }, [])

  return (
    <DataGrid id="gridContainer"
              dataSource={employees}
              keyExpr={"ID"}
              showBorders={true}
              onEditCanceled={onEditCanceled}
              onSaved={onSaved}
    >
      <Editing
        mode="popup"
        allowUpdating={true}>
        <Popup title="Employee Info" showTitle={true} width={700}/>
        <Form>
          <Item itemType="group" colCount={2} colSpan={2}>
            <Item dataField="Prefix"/>
            <Item dataField="FirstName"/>
            <Item dataField="LastName"/>
            <Item dataField="Position"/>
            <Item dataField="BirthDate"/>
            <Item dataField="HireDate"/>
          </Item>
          <Item itemType="group" caption="Photo" colCount={2} colSpan={2}>
            <Item dataField="Picture" colSpan={2}/>
          </Item>
        </Form>
      </Editing>
      <Column dataField="Picture"
              allowSorting={false}
              cellRender={cellRender}
              editCellRender={editCellRender}
      />
      <Column dataField="Prefix"
              width={70}
              caption="Title"
      />
      <Column dataField="FirstName"/>
      <Column dataField="LastName"/>
      <Column dataField="Position"/>
      <Column dataField="BirthDate" dataType="date"/>
      <Column dataField="HireDate" dataType="date"/>
    </DataGrid>
  );
}

export default App;

// Angular/src/app/app.component.ts
import {Component, ViewChild} from '@angular/core';
import {Service, Employee} from './app.service';
import {DxFileUploaderComponent} from 'devextreme-angular';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [Service]
})
export class AppComponent {
  title = 'DataGrid - How to use FileUploader in an edit form';
  employees: Employee[];
  backendURL = 'http://localhost:5000/';
  retryButtonVisible = false;
  @ViewChild('uploadedImage') uploadedImageRef: HTMLImageElement;
  @ViewChild('fileUploader') fileUploaderRef: DxFileUploaderComponent;

  constructor(service: Service) {
    this.employees = service.getEmployees();
  }

  onClick(e) {
    // The retry UI/API is not implemented. Use a private API as shown at T611719.
    const fileUploaderInstance = this.fileUploaderRef.instance;
    // @ts-ignore
    for (let i = 0; i < fileUploaderInstance._files.length; i++) {
      // @ts-ignore
      delete fileUploaderInstance._files[i].uploadStarted;
    }
    // @ts-ignore
    fileUploaderInstance._uploadFiles();
  }

  onValueChanged(e: any) {
    const reader: FileReader = new FileReader();
    reader.onload = (args) => {
      if (typeof args.target.result === 'string') {
        this.uploadedImageRef.src = args.target.result;
      }
    };
    reader.readAsDataURL(e.value[0]); // convert to base64 string
  }

  onUploaded = (e: any, cellInfo: any) => {
    cellInfo.setValue('images/employees/' + e.request.responseText);
    this.retryButtonVisible = false;
  }

  onUploadError = (e: any) => {
    const xhttp = e.request;
    if (xhttp.status === 400) {
      e.message = e.error.responseText;
    }
    if (xhttp.readyState === 4 && xhttp.status === 0) {
      e.message = 'Connection refused';
    }
    this.retryButtonVisible = true;
  }
}

<dx-data-grid id="gridContainer"
  [dataSource]="employees"
  keyExpr="ID"
  [showBorders]="true">

  <dxo-editing
    mode="popup"
    [allowUpdating]="true">
    <dxo-popup
      title="Employee Info"
      [showTitle]="true"
      [width]="700">
    </dxo-popup>
    <dxo-form>
      <dxi-item itemType="group" [colCount]="2" [colSpan]="2">
        <dxi-item dataField="Prefix"></dxi-item>
        <dxi-item dataField="FirstName"></dxi-item>
        <dxi-item dataField="LastName"></dxi-item>
        <dxi-item dataField="Position"></dxi-item>
        <dxi-item dataField="BirthDate"></dxi-item>
        <dxi-item dataField="HireDate"></dxi-item>
      </dxi-item>
      <dxi-item itemType="group" caption="Photo" [colCount]="2" [colSpan]="2">
        <dxi-item dataField="Picture" [colSpan]="2"></dxi-item>
      </dxi-item>
    </dxo-form>
  </dxo-editing>

  <dxi-column dataField="Picture"
              [allowFiltering]="false"
              [allowSorting]="false"
              cellTemplate="cellTemplate"
              editCellTemplate="editCellTemplate">
  </dxi-column>
  <dxi-column dataField="Prefix" [width]="70" caption="Title"></dxi-column>
  <dxi-column dataField="FirstName"></dxi-column>
  <dxi-column dataField="LastName"></dxi-column>
  <dxi-column dataField="Position"></dxi-column>
  <dxi-column dataField="BirthDate" dataType="date"></dxi-column>
  <dxi-column dataField="HireDate" dataType="date"></dxi-column>

  <div *dxTemplate="let data of 'cellTemplate'">
    <img [src]="backendURL + data.value"/>
  </div>
  <div *dxTemplate="let data of 'editCellTemplate'">
    <img #uploadedImage class="uploadedImage" [src]="backendURL + data.value"/>
    <dx-file-uploader
      #fileUploader
      [multiple]="false"
      accept="image/!*"
      uploadMode="instantly"
      [uploadUrl]="backendURL + 'FileUpload/post'"
      (onValueChanged)="onValueChanged($event)"
      (onUploaded)="onUploaded($event, data)"
      (onUploadError)="onUploadError($event)"
    ></dx-file-uploader>
    <dx-button class="retryButton" text="Retry" [visible]="retryButtonVisible" (click)="onClick($event)"></dx-button>
  </div>
</dx-data-grid>
